FROM node:18-alpine

WORKDIR /app

# Copiază package.json
COPY package*.json ./

# Instalează dependențele inclusiv jest
RUN npm install
RUN npm install -g jest

# Copiază restul codului
COPY . .

# Comandă de testare
CMD ["npm", "test"]