FROM node:18-alpine

WORKDIR /app

# Copiază package.json
COPY package*.json ./

# Instalează dependențele
RUN npm install

# Instalează dependențe pentru testele de integrare
RUN npm install -D jest mongodb-memory-server supertest

# Copiază restul codului
COPY . .

# Comandă pentru a rula testele de integrare
# Specifică calea exactă către jest.config.js
CMD ["npm", "run", "test:integration"]