FROM node:18-alpine

WORKDIR /app

# Copiază package.json din directorul principal
# folosește path relativ la build context
COPY package*.json ./

# Instalează dependențele
RUN npm install

# Copiază codul server-ului
COPY . .

# Comandă de testare
CMD ["npm", "test"]